### ISSUE TITLE
Reuse existing JVM if possible

### ISSUE THREAD

**Issue by przemek-pokrywka** [tsk-tsk/tsk-tsk#24]
If `java_version` is not specified, try to find any JVM that might be available on the target system.
If `java_version` is specified and a JVM with that version can be found on the target system, use it, even when Coursier doesn't manage it.

This is to avoid waste of time, bandwidth and disk space.

**Comment by vic** [comment]
Coursier has a `--system-jvm` flag. Haven't got deep into tsk code, but I guess the way to tackle this would be to document that people can set `java_version=system` and don't try to download another jvm, and use the `--system-jvm` flag on `coursier launch`.

Would it be ok if I try to create a PR for this ?

**Comment by przemek-pokrywka** [comment]
Sure thing! Thanks for the suggestion, by all means, please prepare a PR

**Comment by vic** [comment]
Just submitted a firs approach at the following PR #33

**Comment by przemek-pokrywka** [comment]
Thanks for your contribution @vic. I amended it a little bit: if Java is present, it'll be used, otherwise it'll default to version 8.
If one wants to not ever download Java, one can use `java_version=system` but in my opinion normally people would want the java to be downloaded if missing.
