### ISSUE TITLE
URLGrep example doesn't work for me - macos big sur

### ISSUE THREAD

**Issue by jaredmdobson** [tsk-tsk/tsk-tsk#28]
This looks amazing!  Thanks so much for making this, i just tried it on macos big sur 11.2.1 and got this error

```echo "something something http://google.com" | ./URLGrep.scala
Error: Could not find or load main class Compiled from "URLGrep.scala"public final class URLGrep {  public static void main(java.lang.String[]);}```

**Comment by przemek-pokrywka** [comment]
Hi @jaredmdobson, thanks for your kind words! Apparently I've got some fix to do for that system, thanks for spotting.
I think it's near https://github.com/tsk-tsk/tsk-tsk/blob/trunk/tsk#L466 but would need to spend some time on CI setup and testing (I'm on Linux).

In the meanwhile I'd recommend you to set the main class explicitly with the `main_class=URLGrep;` as yet another part of the preamble (but before `run`).

**Comment by jaredmdobson** [comment]
@przemek-pokrywka that did it!!! Thank you so much! 🔥

 ![](https://media0.giphy.com/media/Pn0gCV1oBkr3OUNc21/giphy.gif)

**Comment by przemek-pokrywka** [comment]
I'm glad that the workaroud worked for you, but the problem with main class detection is real unfortunately :disappointed:. For that reason I'm reopening the bug.

**Comment by przemek-pokrywka** [comment]
Fixed properly with https://github.com/tsk-tsk/tsk-tsk/commit/dfc11f58eca020b496de96ff6f034db659a23fb1

it was probably an ancient version of sed used by default on macs, likely it doesn't understand the regex groups.

Thanks again for reporting @jaredmdobson
