### ISSUE TITLE
Executable scala file not able to run on fish

### ISSUE THREAD

**Issue by vic** [tsk-tsk/tsk-tsk#34]
Having the following preamble at an `example.scala` file with the executable bit set, I'm able to run `./example.scala` in both Bash and Zsh, however fish-shell complains with the error bellow.

```
// 2> /dev/null; source $(curl -sL https://git.io/boot-tsk | sh); run; exit
```

fish error:
```
❯ ./example.scala
Failed to execute process './example.scala'. Reason:
exec: Exec format error
The file './example.scala' is marked as an executable but could not be run by the operating system.
```

**Comment by vic** [comment]
Related https://github.com/fish-shell/fish-shell/issues/1281#issuecomment-265788224

So I guess there's nothing we can do unless we used a proper `#!` shebang on our scripts first line.

Feel free to close.

**Comment by przemek-pokrywka** [comment]
Hi @vic, thanks for reporting, yes, I agree, nothing can be done in the current situation if we want to:
- avoid Scala compiler complaining about shebang (https://github.com/scala/bug/issues?q=shebang)
- avoid having to fix Fish

for now I've just mentioned it in limitations section of the docs: https://github.com/tsk-tsk/tsk-tsk/wiki#limitations-known-issues
